title: Hyde
description: Just a blog
baseurl: "/study"
url: "https://jayisthere.github.io"

remote_theme: poole/hyde

plugins:
  - jekyll-feed
  - jekyll-seo-tag


paginate:         5
relative_permalinks: true

markdown:         redcarpet
highlighter:      pygments
